import "./globals.css";
import { Inter } from "next/font/google";
import { ClientProvider } from "@/utils/trpc-provider";
import Provider from "@/utils/provider";
import { NextAuthSessionProvider } from "@/utils/SessionProvider";
import DnDProvider from "@/utils/DndProvider";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextAuthSessionProvider>
          <ClientProvider>
            <DnDProvider>
              <Provider>
                <main>{children}</main>
                <Toaster />
              </Provider>
            </DnDProvider>
          </ClientProvider>
        </NextAuthSessionProvider>
      </body>
    </html>
  );
}
