import "./globals.css";
import { Inter } from "next/font/google";
import { ClientProvider } from "@/utils/trpc-provider";
import Provider from "@/utils/provider";
import { db } from "@/db/postgres-drizzle";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ClientProvider>
          <Provider>
            <main>{children}</main>
          </Provider>
        </ClientProvider>
      </body>
    </html>
  );
}
